GET https://tyll-fn.azurewebsites.net/api/getpersonbyidfn

@token = JqAJa72mUr0aXGbp/BDtDSejUtaKBadpyQ7aqYea/m2CgkULaLmMQA==


//POST https://developerlifefn.azurewebsites.net/api/AddPersonFn?code={{token}}
POST https://tyll-fn.azurewebsites.net/api/AddPersonFn?code=ws-SI94caJkpmfD7pUcQoOmRFCLjkKv8X7Lll_5mSVEmAzFuGEgIiw==
Content-Type: "application/json"

{
    "firstname":"karolina",
    "lastname":"karolinska"
}

PUT https://tyll-fn.azurewebsites.net/api/UpdatePersonFn?code=gKAniSxg0y5PQN7qJIrxDsY2ftAHt7iEeLGLo3Vtlv0uAzFuK5l4WQ==
Content-Type: "application/json"

{
    "personid":2,
    "firstname":"karolina",
    "lastname":"kiedys-karolinska"
}
    